### ISSUE TITLE
Fantastic work! :)

### ISSUE THREAD

**Issue by asigalov61** [Wally869/MidiGenerator#2]
Hey Wally 👍 

Just wanted to say hi and thank you for your great work on MIDIGenerator. I think it has great potential and I will definitely follow your project.

Check out my Github as I am also working on similar music projects which may be of interest to you. 

And if you want to colab/chat/exchange ideas/knowledge - def. let me know :)

Sincerely,

Alex

**Comment by Wally869** [comment]
Hey Asigalov

Glad you find it interesting! The repo is really messy, I was a bit confused with what approach to take so it was on the backburner for a while, but you can expect some new updates soon. 

I fixed most of the issues currently plaguing the repo with b8eebf80c286c07f34ee768b9de1e5ee12d01552 and 3874fedc972ede6b7668a599cfafd8b5146e35dd (Replaced MidiStructurer reference by MusiStrata, and fixed usage of deprecated functions), so SampleTest.py and Test_SectionComponents.py are working properly now, and they contain the 2 approaches I was thinking about when I started working on this, so you can check it out now! Generated samples are pretty random for now, but I'll replace them soon.

I took a look at your github and it's full of interesting stuff. Thanks for sharing, I'll definitely spend some time going through your repos!

Sincerely,
William

**Comment by asigalov61** [comment]
Hey William,

Yes, thank you so much for a prompt reply and for fixing the issues. Much appreciated. I will try to run the generator again and I will let you know if there are any problems. And thank you for the info.

Yes, algo music is not easy and it's a brand new field of study so there are a lot of unknowns and outright brand new things to figure out. So do not feel bad if you lose your direction once in a while...it just takes perseverance and time from my experience.

And definitely check out my repos as I collected I think all of GitHub in regard to computer music generation and music composition and there is a lot of things that can be learned from all that stuff. I did huge progress IMHO with generating interesting and listenable music so, I think there is a lot of potential in the algorithmic approach.

Please let me know if you will find any of my stuff interesting and if you want to colab as I am interested in working together with someone on one of these projects.

Anyway, thank you again for your response and fixes.

Sincerely,

Alex

**Comment by asigalov61** [comment]
Yes, it works! Thank you so much! And it does generate nice melodies and chords, all things considered. I know that it is a work in progress so do not sweat it...take your time.

I use AI techniques in my algo generator but your formula is a solid approach too, so definitely work on it 👍 

And please let me know if you have any questions or if you need help with anything related to algo music. I will be happy to help however I can

thanks.
